### ISSUE TITLE
Invalid json response

### ISSUE THREAD

**Issue by amit-sides** [ecoppen/futuresboard#109]
**Describe the problem**
While trying to execute `send_signed_request`, the scraper crashed on this line `json_response = response.json()`.
It returned the exception `requests.exceptions.JSONDecodeError`, which was never caught.

**To Reproduce**
Don't really know how to reproduce it because it occurred due to an invalid response from the server.

**Expected behavior**
Since this is an unexpected error, it should be caught and logged appropriately, without crashing the scraper.

**Traceback**
```python
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 971, in json
     return complexjson.loads(self.text, **kwargs)
   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
     return _default_decoder.decode(s)
   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.8/site-packages/futuresboard/scraper.py", line 43, in _auto_scrape
     scrape(app=app)
   File "/usr/local/lib/python3.8/site-packages/futuresboard/scraper.py", line 280, in scrape
     _scrape(app=app)
   File "/usr/local/lib/python3.8/site-packages/futuresboard/scraper.py", line 529, in _scrape
     responseHeader, responseJSON = send_signed_request(
   File "/usr/local/lib/python3.8/site-packages/futuresboard/scraper.py", line 98, in send_signed_request
     json_response = response.json()
   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 975, in json
     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
 requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ecoppen** [comment]
Did the scraper continue automatically after the `scrape_interval` time or did the whole application crash? 

I can add a catch for this.

**Comment by amit-sides** [comment]
The scraper thread crashed completely, it required a manual restart

**Comment by amit-sides** [comment]
I believe this should fix the crash. If I encounter this exception's log I will update here...
