### ISSUE TITLE
--scrape-only fails with 'NoneType' object has no attribute 'logger'

### ISSUE THREAD

**Issue by kkoouu** [ecoppen/futuresboard#123]
When running futuresboard with --scrape-only, I'm getting immediate error:

```
Traceback (most recent call last):
  File "/opt/py3.11-venv/bin/futuresboard", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/py3.11-venv/lib/python3.11/site-packages/futuresboard/cli.py", line 64, in main
    futuresboard.scraper.scrape()
  File "/opt/py3.11-venv/lib/python3.11/site-packages/futuresboard/scraper.py", line 318, in scrape
    _scrape(app=app)
  File "/opt/py3.11-venv/lib/python3.11/site-packages/futuresboard/scraper.py", line 468, in _scrape
    app.logger.info("Deleting orders and positions from db")
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'logger'

```
Without --scrape-only app runs fine, i'm using main branch, looks like "app" is not defined

**Comment by Jeerjmin** [comment]
Same issue
