### ISSUE TITLE
Error after command 'futuresboad'

### ISSUE THREAD

**Issue by aumanusorn** [ecoppen/futuresboard#36]
Traceback (most recent call last):
  File "/usr/bin/futuresboard", line 33, in <module>
    sys.exit(load_entry_point('futuresboard', 'console_scripts', 'futuresboard')())
  File "/usr/bin/futuresboard", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: futuresboard

**Comment by ecoppen** [comment]
Hopefully this issue has been resolved, please reopen if not!
