### ISSUE TITLE
Error on poisitons

### ISSUE THREAD

**Issue by riodda** [ecoppen/futuresboard#48]
I have internal server erro on Positions

```
[2022-01-18 10:51:56,932] INFO in scraper: Auto scrape routines terminated. Sleeping 600 seconds...
192.168.1.176 - - [18/Jan/2022 11:00:48] "GET / HTTP/1.1" 200 -
192.168.1.176 - - [18/Jan/2022 11:00:48] "GET /static/styles/dashboard.css HTTP/1.1" 304 -
192.168.1.176 - - [18/Jan/2022 11:00:48] "GET /static/styles/sidebars.css HTTP/1.1" 304 -
192.168.1.176 - - [18/Jan/2022 11:00:48] "GET /static/js/chartjs-chart-financial.js HTTP/1.1" 304 -
192.168.1.176 - - [18/Jan/2022 11:00:48] "GET /static/js/hammer.min.js HTTP/1.1" 304 -
192.168.1.176 - - [18/Jan/2022 11:00:49] "GET /static/favicon2.ico HTTP/1.1" 304 -
[2022-01-18 11:00:53,100] ERROR in app: Exception on /positions [GET]
Traceback (most recent call last):
  File "/home/dario/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dario/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dario/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dario/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dario/.local/lib/python3.8/site-packages/futuresboard/blueprint.py", line 603, in positions_page
    return render_template(
  File "/home/dario/.local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/dario/.local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/dario/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/dario/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dario/.local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/dario/.local/lib/python3.8/site-packages/futuresboard/templates/base.html", line 108, in top-level template code
    <div id="content">{% block content %}{% endblock %}</div>
  File "/home/dario/.local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 47, in block 'content'
    <td>{{ ((1-positions[coin][2][4]/markprices[coin])*100)|round(2)}}%</td>
TypeError: unsupported operand type(s) for /: 'str' and 'float'
192.168.1.176 - - [18/Jan/2022 11:00:53] "GET /positions HTTP/1.1" 500 -
192.168.1.176 - - [18/Jan/2022 11:00:53] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.176 - - [18/Jan/2022 11:00:54] "GET /static/favicon2.ico HTTP/1.1" 304 -

```

**Comment by ecoppen** [comment]
Just to check, are there no sell orders left for a particular coin/position? [This commit](https://github.com/ecoppen/futuresboard/commit/e5ae3a624a77ccb74619af182a8c00ca7e78092c) fixed the one for no buys, so I'm assuming there are no sells?

**Comment by riodda** [comment]
I had one manual sell on a position of a coin i stop trading with passivbot, but that order triggerd already the day before yesterday. 
I don't recon any order/position that don't belong to my passivbot instances.
