### ISSUE TITLE
Bybit no longer compatible due to API change?

### ISSUE THREAD

**Issue by donewiththedollar** [ecoppen/futuresboard#74]
The error I am getting upon starting futuresboard using bybit:

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/futuresboard", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/cli.py", line 64, in main
    futuresboard.scraper.scrape()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/scraper.py", line 274, in scrape
    _scrape(app=app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/scraper.py", line 530, in _scrape
    if responseJSON["result"]["data"] is not None:
KeyError: 'data'`

Have asked others about the issue in PB discord, it appears works fine on Binance but no longer on Bybit. I looked through their API changes and cannot seem to spot a modification that could be causing this error.

**Comment by ecoppen** [comment]
Added the suggested fix from discord, if possible can you verify? https://github.com/ecoppen/futuresboard/tree/fix-bybit

**Comment by donewiththedollar** [comment]
Issue resolved!
```
                if responseJSON["result"] is not None:
                    if "data" in responseJSON["result"].keys() and responseJSON["result"]["data"] is not None:
```
