### ISSUE TITLE
App crashes on positions request

### ISSUE THREAD

**Issue by amit-sides** [ecoppen/futuresboard#80]
I'm using bybit and running futuresboard using docker-compose.
The app triggered an exception and returned `500 Internal Server Error` for me once (very rarely), probably because of unexpected value from the data...

```python
futuresboard_1  | [2022-11-29 22:41:44,265] ERROR in app: Exception on /positions [GET]
futuresboard_1  | Traceback (most recent call last):
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
futuresboard_1  |     response = self.full_dispatch_request()
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
futuresboard_1  |     rv = self.handle_user_exception(e)
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
futuresboard_1  |     rv = self.dispatch_request()
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
futuresboard_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/futuresboard/blueprint.py", line 665, in positions_page
futuresboard_1  |     return render_template(
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
futuresboard_1  |     return _render(app, template, context)
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
futuresboard_1  |     rv = template.render(context)
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
futuresboard_1  |     self.environment.handle_exception()
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
futuresboard_1  |     raise rewrite_traceback_stack(source=source)
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 1, in top-level template code
futuresboard_1  |     {% extends "base.html" %}
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/futuresboard/templates/base.html", line 113, in top-level template code
futuresboard_1  |     <div id="content">{% block content %}{% endblock %}</div>
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 39, in block 'content'
futuresboard_1  |     <td>{{ markprices[coin]|round(8)}}</td>
futuresboard_1  |   File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 1141, in do_round
futuresboard_1  |     return round(value, precision)
futuresboard_1  | TypeError: type Undefined doesn't define __round__ method
futuresboard_1  | *.*.*.* - - [29/Nov/2022 22:41:44] "GET /positions HTTP/1.1" 500 -
```

**Comment by ecoppen** [comment]
Latest bybit API appears to be more stable and should be fixed in v1. Please reopen if not and I'lll attempt another fix for v1 and v2.
